OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Doctor
    Domain: doctor.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  
  - Name: Patient
    Domain: patient.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  
  - Name: Pharmacy
    Domain: pharmacy.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  
  - Name: Regulatory
    Domain: regulatory.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1